"""empty message

Revision ID: 0648fa7aabd1
Revises: 40b953b5d4fc
Create Date: 2025-08-26 12:01:01.183850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0648fa7aabd1'
down_revision: Union[str, None] = '40b953b5d4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('individual', 'estado_civil',
               existing_type=mysql.ENUM('CASADO', 'SOLTEIRO', 'VIUVO', 'DIVOCIADO', 'SEPARADO', 'UNIAO'),
               type_=sa.Enum('CASADO', 'SOLTEIRO', 'VIUVO', 'DIVORCIADO', 'SEPARADO', 'UNIAO', name='estadociviltype'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('individual', 'estado_civil',
               existing_type=sa.Enum('CASADO', 'SOLTEIRO', 'VIUVO', 'DIVORCIADO', 'SEPARADO', 'UNIAO', name='estadociviltype'),
               type_=mysql.ENUM('CASADO', 'SOLTEIRO', 'VIUVO', 'DIVOCIADO', 'SEPARADO', 'UNIAO'),
               existing_nullable=True)
    # ### end Alembic commands ###
