"""empty message

Revision ID: 40b953b5d4fc
Revises: a645b18215ca
Create Date: 2025-08-25 12:56:18.564253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b953b5d4fc'
down_revision: Union[str, None] = 'a645b18215ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual', sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('individual', sa.Column('data_atualizacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('individual', 'data_atualizacao')
    op.drop_column('individual', 'data_criacao')
    # ### end Alembic commands ###
