"""empty message

Revision ID: d9c79ec83145
Revises: 0648fa7aabd1
Create Date: 2025-08-26 17:42:11.349109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c79ec83145'
down_revision: Union[str, None] = '0648fa7aabd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('titulo', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=120), nullable=True),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['individual_id'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_address_individual_id'), 'individual_address', ['individual_id'], unique=False)
    op.create_table('individual_email',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['individual_id'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_email_individual_id'), 'individual_email', ['individual_id'], unique=False)
    op.create_table('individual_phone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('whatsapp', sa.SmallInteger(), nullable=True),
    sa.Column('procon', sa.SmallInteger(), nullable=True),
    sa.Column('blocklist', sa.SmallInteger(), nullable=True),
    sa.Column('hot', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['individual_id'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_phone_individual_id'), 'individual_phone', ['individual_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individual_phone_individual_id'), table_name='individual_phone')
    op.drop_table('individual_phone')
    op.drop_index(op.f('ix_individual_email_individual_id'), table_name='individual_email')
    op.drop_table('individual_email')
    op.drop_index(op.f('ix_individual_address_individual_id'), table_name='individual_address')
    op.drop_table('individual_address')
    # ### end Alembic commands ###
